# Generated by Django 4.1.3 on 2022-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('perfil', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=100)),
                ('nivel', models.CharField(choices=[('junior', 'Junior'), ('semisenior', 'Semisenior'), ('senior', 'Senior')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
